/**
 * PRODX POS - Default Configuration Datasets for 100% Comprehensive System Management
 */

import {
  SystemModuleConfig,
  QuickKeyItem,
  PaymentMethodItem,
  DiscountPresetItem,
  TaxBracketItem,
  LoyaltyEngineConfig,
  ReceiptTemplateConfig,
} from './types';

export const DEFAULT_MODULES_CONFIG: SystemModuleConfig[] = [
  {
    id: 'pos',
    code: 'MOD_POS',
    name: { th: 'จุดขายและแคชเชียร์ (POS Checkout)', en: 'POS Checkout & Register' },
    description: {
      th: 'ระบบคิดเงินหลัก, จัดการตะกร้าสินค้า, สแกนบาร์โค้ด, พักบิล และชำระเงินด่วน',
      en: 'Primary checkout flow, cart management, barcode scanning, hold/recall, and fast tenders.',
    },
    iconName: 'ShoppingCart',
    color: 'primary',
    enabled: true,
    defaultRoute: 'pos',
    badge: 'Core',
    features: [
      {
        id: 'pos_barcode_scan',
        name: { th: 'ระบบสแกนบาร์โค้ดความเร็วสูง', en: 'High-speed Barcode Scanner' },
        description: { th: 'รองรับเครื่องสแกนบาร์โค้ด USB/HID/Serial', en: 'Supports USB/HID/Serial barcode scanners' },
        enabled: true,
      },
      {
        id: 'pos_split_payment',
        name: { th: 'การแยกชำระหลายช่องทาง (Split Payment)', en: 'Split Payment Tender' },
        description: { th: 'ชำระเงินสดร่วมกับบัตรเครดิตหรือโอนเงินในบิลเดียว', en: 'Split single ticket into multiple tender types' },
        enabled: true,
      },
      {
        id: 'pos_hold_cart',
        name: { th: 'พักบิล / เรียกคืนบิลชั่วคราว (Hold & Recall)', en: 'Hold & Recall Orders' },
        description: { th: 'บันทึกตะกร้าเพื่อรองรับลูกค้าคิวถัดไปได้ทันที', en: 'Temporarily park transactions for multi-queue handling' },
        enabled: true,
      },
      {
        id: 'pos_custom_item',
        name: { th: 'เพิ่มสินค้าราคากำหนดเอง (Custom Item)', en: 'Custom Price Line Items' },
        description: { th: 'อนุญาตให้ระบุชื่อสินค้าและราคาอิสระหน้างาน', en: 'Allow ad-hoc custom items during checkout' },
        enabled: true,
      },
      {
        id: 'pos_kitchen_print',
        name: { th: 'ส่งรายการเข้าเครื่องพิมพ์ครัว (Kitchen Ticket)', en: 'Kitchen Order Routing' },
        description: { th: 'แยกพิมพ์ใบสั่งอาหาร/เครื่องดื่มเข้าบาร์หรือครัว', en: 'Auto-print kitchen and bar preparation slips' },
        enabled: true,
      },
      {
        id: 'pos_ai_upsell',
        name: { th: 'AI แนะนำสินค้าขายดีคู่กัน (Smart Upsell)', en: 'AI Co-Purchase Suggestions' },
        description: { th: 'ระบบ AI วิเคราะห์สินค้าที่มักซื้อร่วมกันแบบเรียลไทม์', en: 'AI model suggests best complementary items' },
        enabled: true,
      },
    ],
  },
  {
    id: 'inventory',
    code: 'MOD_INV',
    name: { th: 'คลังสินค้าและสต็อก (Inventory & Catalog)', en: 'Inventory & Stock Ledger' },
    description: {
      th: 'จัดการรายการสินค้า, บาร์โค้ด, หมวดหมู่, สต็อกการ์ด, บันทึกการเคลื่อนไหว และการนำเข้าข้อมูล',
      en: 'Product master data, category tree, immutable stock ledger, and bulk CSV/JSON import.',
    },
    iconName: 'Boxes',
    color: 'emerald',
    enabled: true,
    defaultRoute: 'inventory',
    badge: 'Real-time',
    features: [
      {
        id: 'inv_low_stock_alert',
        name: { th: 'การแจ้งเตือนสต็อกใกล้หมด (Low Stock Alerts)', en: 'Low Stock Trigger' },
        description: { th: 'แจ้งเตือนเมื่อจำนวนคงเหลือต่ำกว่าจุดสั่งซื้อขั้นต่ำ', en: 'Live visual badges when inventory drops below safety point' },
        enabled: true,
      },
      {
        id: 'inv_bulk_upload',
        name: { th: 'นำเข้าข้อมูลสินค้าจำนวนมาก (Bulk CSV/JSON)', en: 'Bulk CSV/JSON Import' },
        description: { th: 'อัปโหลด ปรับปรุง และตรวจสอบสต็อกด้วยไฟล์', en: 'Enterprise CSV/JSON batch catalog import engine' },
        enabled: true,
      },
      {
        id: 'inv_shelf_label',
        name: { th: 'เครื่องมือพิมพ์ป้ายราคาและบาร์โค้ด (Shelf Labels)', en: 'Shelf Label Generator' },
        description: { th: 'จัดรูปแบบและพิมพ์ป้ายบาร์โค้ดติดชั้นวางสินค้า', en: 'Generate printable barcode labels and price tags' },
        enabled: true,
      },
      {
        id: 'inv_negative_stock',
        name: { th: 'อนุญาตให้ขายเมื่อสินค้าติดลบ (Allow Backorders)', en: 'Allow Negative Stock' },
        description: { th: 'ทำการขายได้แม้จำนวนสต็อกในระบบระบุเป็น 0', en: 'Allow sales even when on-hand stock count is zero' },
        enabled: false,
      },
    ],
  },
  {
    id: 'orders',
    code: 'MOD_ORD',
    name: { th: 'ประวัติคำสั่งซื้อและใบเสร็จ (Orders & Receipts)', en: 'Order History & Refunds' },
    description: {
      th: 'ตรวจสอบประวัติการขายย้อนหลัง, พิมพ์ใบเสร็จซ้ำ, จัดการการยกเลิกบิล และการคืนเงิน',
      en: 'Historical sales records, receipt reprints, transaction voids, and refund governance.',
    },
    iconName: 'ReceiptText',
    color: 'blue',
    enabled: true,
    defaultRoute: 'orders',
    features: [
      {
        id: 'ord_reprint',
        name: { th: 'พิมพ์สำเนาใบเสร็จรับเงิน (Receipt Reprints)', en: 'Receipt Reprints' },
        description: { th: 'พิมพ์ซ้ำใบเสร็จรับเงินพร้อมตราประทับสำเนา', en: 'Reprint receipts marked with DUPLICATE copy watermarks' },
        enabled: true,
      },
      {
        id: 'ord_void_refund',
        name: { th: 'การยกเลิกบิลและการคืนเงิน (Void & Refund)', en: 'Void & Refund Controls' },
        description: { th: 'กระบวนการคืนเงินพร้อมบันทึกเหตุผลและคืนสต็อกอัตโนมัติ', en: 'Controlled refund flow with audit reasoning & stock restock' },
        enabled: true,
      },
      {
        id: 'ord_tax_invoice',
        name: { th: 'ออกใบกำกับภาษีเต็มรูป (Full Tax Invoice)', en: 'Full Tax Invoicing' },
        description: { th: 'บันทึกข้อมูลผู้เสียภาษีและพิมพ์ใบกำกับภาษีตามกฎหมาย', en: 'Issue certified tax invoices with corporate details' },
        enabled: true,
      },
    ],
  },
  {
    id: 'shift',
    code: 'MOD_SHF',
    name: { th: 'กะการทำงานและลิ้นชักเงินสด (Shift & Cash Drawer)', en: 'Shift & Cash Float' },
    description: {
      th: 'เปิด/ปิดกะแคชเชียร์, ตรวจนับเงินสด, บันทึกเงินเข้า/ออก, รายงาน X-Report และ Z-Report',
      en: 'Shift opening/closing, float management, pay-in/pay-out, X-reading, and Z-report reconciliation.',
    },
    iconName: 'Banknote',
    color: 'amber',
    enabled: true,
    defaultRoute: 'shift',
    features: [
      {
        id: 'shf_blind_close',
        name: { th: 'การปิดกะแบบไม่แสดงยอดเงินล่วงหน้า (Blind Close)', en: 'Blind Shift Close' },
        description: { th: 'ให้แคชเชียร์นับเงินจริงโดยไม่เห็นยอดที่ระบบคำนวณไว้', en: 'Cashier counts cash without seeing expected system balance' },
        enabled: true,
      },
      {
        id: 'shf_cash_in_out',
        name: { th: 'บันทึกเงินเข้า/ออกลิ้นชัก (Pay-In / Pay-Out)', en: 'Cash In / Out Ledger' },
        description: { th: 'บันทึกการเบิกจ่ายเงินสดสดย่อยพร้อมระบุเหตุผล', en: 'Track petty cash disbursements and mid-shift deposits' },
        enabled: true,
      },
      {
        id: 'shf_auto_kick',
        name: { th: 'เตะลิ้นชักเงินสดอัตโนมัติเมื่อรับเงินสด', en: 'Auto Drawer Kick' },
        description: { th: 'ส่งสัญญาณเปิดลิ้นชักอัตโนมัติเมื่อทำรายการสำเร็จ', en: 'Send electrical pulse to cash drawer upon cash checkout' },
        enabled: true,
      },
    ],
  },
  {
    id: 'customers',
    code: 'MOD_CRM',
    name: { th: 'ลูกค้าสัมพันธ์และแต้มสะสม (Customers & Loyalty CRM)', en: 'Customers & Loyalty CRM' },
    description: {
      th: 'ฐานข้อมูลสมาชิก, บันทึกแต้มสะสม, สิทธิ์ส่วนลดระดับ VIP และประวัติการซื้อ',
      en: 'Customer directory, point accumulation, VIP loyalty tiers, and purchasing insights.',
    },
    iconName: 'Users',
    color: 'purple',
    enabled: true,
    defaultRoute: 'customers',
    badge: 'Loyalty',
    features: [
      {
        id: 'crm_points_engine',
        name: { th: 'ระบบสะสมและแลกแต้มคะแนน (Points Engine)', en: 'Points Engine' },
        description: { th: 'สะสมคะแนนจากการซื้อสินค้าและใช้แต้มเป็นส่วนลด', en: 'Earn points per currency spent and redeem for bill discounts' },
        enabled: true,
      },
      {
        id: 'crm_vip_tiers',
        name: { th: 'ระดับสมาชิกลำดับขั้น (VIP Membership Tiers)', en: 'VIP Membership Tiers' },
        description: { th: 'สิทธิประโยชน์อัตโนมัติตามระดับ Bronze, Silver, Gold, Platinum', en: 'Automatic tier multipliers and exclusive member discounts' },
        enabled: true,
      },
      {
        id: 'crm_credit_limit',
        name: { th: 'วงเงินเชื่อลูกค้า (Customer Store Credit)', en: 'Store Credit & Debt' },
        description: { th: 'บันทึกยอดค้างชำระและวงเงินเชื่อสำหรับลูกค้าองค์กร', en: 'Maintain store ledger for account receivable clients' },
        enabled: true,
      },
    ],
  },
  {
    id: 'dashboard',
    code: 'MOD_ANA',
    name: { th: 'วิเคราะห์ยอดขายและรายงาน (Analytics Dashboard)', en: 'Analytics & Reporting' },
    description: {
      th: 'กราฟยอดขายเรียลไทม์, แผนที่ความร้อนช่วงเวลา, สินค้าขายดี, กำไรขั้นต้น และส่งออกรายงาน',
      en: 'Real-time sales velocity, peak-hour heatmaps, top-seller analytics, and profit margins.',
    },
    iconName: 'LayoutGrid',
    color: 'indigo',
    enabled: true,
    defaultRoute: 'dashboard',
    features: [
      {
        id: 'ana_hourly_heatmap',
        name: { th: 'วิเคราะห์ช่วงเวลาขายดี (Hourly Heatmap)', en: 'Hourly Sales Heatmap' },
        description: { th: 'แสดงความหนาแน่นของลูกค้าและยอดขายในแต่ละชั่วโมง', en: 'Visual heatmap showing store peak traffic hours' },
        enabled: true,
      },
      {
        id: 'ana_margin_calc',
        name: { th: 'รายงานกำไรขั้นต้น (Gross Profit Margin)', en: 'Gross Profit Calculations' },
        description: { th: 'คำนวณกำไรเทียบระหว่างราคาทุนและราคาขายจริง', en: 'Compare cost of goods vs retail revenue' },
        enabled: true,
      },
      {
        id: 'ana_export_csv',
        name: { th: 'ส่งออกรายงานข้อมูล (Data Exports)', en: 'Executive Data Exports' },
        description: { th: 'ดาวน์โหลดไฟล์รายงาน Excel/CSV สำหรับฝ่ายบัญชี', en: 'Export clean structured datasets for accounting' },
        enabled: true,
      },
    ],
  },
  {
    id: 'audit',
    code: 'MOD_AUD',
    name: { th: 'บันทึกความปลอดภัยและตรวจสอบ (Audit Trail & Security)', en: 'Audit Trail & Compliance' },
    description: {
      th: 'บันทึกการกระทำสำคัญในระบบ ตรวจสอบการยกเลิกบิล ส่วนลด การเปิดลิ้นชัก และการแก้ไขข้อมูล',
      en: 'Immutable security log stream, manager override tracking, and tamper verification.',
    },
    iconName: 'ShieldCheck',
    color: 'rose',
    enabled: true,
    defaultRoute: 'audit',
    badge: 'Security',
    features: [
      {
        id: 'aud_realtime_events',
        name: { th: 'ติดตามเหตุการณ์แบบเรียลไทม์ (Live Event Stream)', en: 'Live Event Stream' },
        description: { th: 'แสดงบันทึกการกระทำของผู้ใช้ทุกคนในทันที', en: 'Real-time stream of all cashier and manager operations' },
        enabled: true,
      },
      {
        id: 'aud_tamper_seal',
        name: { th: 'ระบบตรวจสอบความสมบูรณ์ของข้อมูล (Integrity Checks)', en: 'Tamper Verification' },
        description: { th: 'ตรวจสอบความถูกต้องของการบันทึกข้อมูลไม่ให้ถูกดัดแปลง', en: 'Cryptographic hash checks against log modifications' },
        enabled: true,
      },
    ],
  },
  {
    id: 'customerDisplay',
    code: 'MOD_CFD',
    name: { th: 'จอแสดงผลฝั่งลูกค้า (Customer Facing Display - CFD)', en: 'Customer Facing Display (CFD)' },
    description: {
      th: 'หน้าจอคู่สำหรับลูกค้า แสดงรายการสินค้าสด QR Code พร้อมเพย์ และสื่อโฆษณาโปรโมชั่น',
      en: 'Dual-screen customer visual terminal with live basket mirror, dynamic QR, and media loop.',
    },
    iconName: 'Tv',
    color: 'cyan',
    enabled: true,
    badge: 'Dual-Screen',
    features: [
      {
        id: 'cfd_live_cart',
        name: { th: 'สะท้อนตะกร้าสินค้าแบบเรียลไทม์ (Live Cart Mirror)', en: 'Live Cart Mirror' },
        description: { th: 'แสดงรายการสินค้า ราคารวม และส่วนลดให้ลูกค้าเห็นทันที', en: 'Broadcasts line items and total pricing instantaneously' },
        enabled: true,
      },
      {
        id: 'cfd_qr_prompt',
        name: { th: 'แสดง QR PromptPay รับเงินอัตโนมัติ', en: 'Dynamic QR Payment Prompt' },
        description: { th: 'สร้าง QR Code พร้อมเพย์ตามยอดบิลให้ลูกค้าสแกนจ่ายบนหน้าจอ', en: 'Auto-generate dynamic PromptPay QR on the customer screen' },
        enabled: true,
      },
      {
        id: 'cfd_promo_banner',
        name: { th: 'สไลด์โฆษณาและวิดีโอพักหน้าจอ (Promo Slideshow)', en: 'Promotional Slideshow' },
        description: { th: 'หมุนเวียนภาพโปรโมชั่นสินค้าเมื่อไม่มีรายการขาย', en: 'Loop marketing visuals and announcements during idle state' },
        enabled: true,
      },
    ],
  },
];

export const DEFAULT_QUICK_KEYS: QuickKeyItem[] = [
  {
    id: 'qk-1',
    label: 'กาแฟเอสเพรสโซ่ร้อน',
    sku: 'BEV-HOT-ESP',
    price: 55,
    actionType: 'add_product',
    color: 'amber',
    iconName: 'Coffee',
    sortOrder: 1,
    isEnabled: true,
  },
  {
    id: 'qk-2',
    label: 'ชาเขียวมัทฉะเย็น',
    sku: 'BEV-ICE-MAT',
    price: 65,
    actionType: 'add_product',
    color: 'emerald',
    iconName: 'CupSoda',
    sortOrder: 2,
    isEnabled: true,
  },
  {
    id: 'qk-3',
    label: 'น้ำแร่ธรรมชาติ 500ml',
    sku: 'BEV-WAT-500',
    price: 15,
    actionType: 'add_product',
    color: 'cyan',
    iconName: 'Droplets',
    sortOrder: 3,
    isEnabled: true,
  },
  {
    id: 'qk-4',
    label: 'ครัวซองต์เนยสดแท้',
    sku: 'BAK-CR-001',
    price: 75,
    actionType: 'add_product',
    color: 'orange',
    iconName: 'Cookie',
    sortOrder: 4,
    isEnabled: true,
  },
  {
    id: 'qk-5',
    label: 'ส่วนลดพิเศษ 10%',
    actionType: 'discount',
    color: 'rose',
    iconName: 'Percent',
    sortOrder: 5,
    isEnabled: true,
  },
  {
    id: 'qk-6',
    label: 'เตะเปิดลิ้นชัก (No Sale)',
    actionType: 'open_drawer',
    color: 'indigo',
    iconName: 'Unlock',
    sortOrder: 6,
    isEnabled: true,
  },
  {
    id: 'qk-7',
    label: 'พิมพ์ใบเสร็จล่าสุดซ้ำ',
    actionType: 'print_last',
    color: 'slate',
    iconName: 'Printer',
    sortOrder: 7,
    isEnabled: true,
  },
  {
    id: 'qk-8',
    label: 'เพิ่มสินค้าแบบกำหนดเอง',
    actionType: 'custom_amount',
    color: 'primary',
    iconName: 'PlusCircle',
    sortOrder: 8,
    isEnabled: true,
  },
];

export const DEFAULT_PAYMENT_METHODS: PaymentMethodItem[] = [
  {
    id: 'pay-cash',
    name: 'เงินสด (Cash)',
    code: 'CASH',
    type: 'cash',
    iconName: 'Banknote',
    color: 'emerald',
    feePercent: 0,
    minAmount: 0,
    requireApproval: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    id: 'pay-promptpay',
    name: 'พร้อมเพย์ QR (PromptPay)',
    code: 'PROMPTPAY',
    type: 'qr',
    iconName: 'QrCode',
    color: 'cyan',
    feePercent: 0,
    minAmount: 1,
    requireApproval: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    id: 'pay-card',
    name: 'บัตรเครดิต/เดบิต (Credit/Debit Card)',
    code: 'CREDIT_CARD',
    type: 'card',
    iconName: 'CreditCard',
    color: 'indigo',
    feePercent: 1.5,
    minAmount: 100,
    requireApproval: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    id: 'pay-truemoney',
    name: 'TrueMoney Wallet',
    code: 'TRUEMONEY',
    type: 'ewallet',
    iconName: 'Smartphone',
    color: 'orange',
    feePercent: 0.9,
    minAmount: 10,
    requireApproval: false,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    id: 'pay-rabbitline',
    name: 'Rabbit LINE Pay',
    code: 'LINEPAY',
    type: 'ewallet',
    iconName: 'Smartphone',
    color: 'emerald',
    feePercent: 1.2,
    minAmount: 10,
    requireApproval: false,
    isEnabled: true,
    sortOrder: 5,
  },
  {
    id: 'pay-alipay',
    name: 'Alipay / WeChat Pay',
    code: 'ALIPAY_WECHAT',
    type: 'ewallet',
    iconName: 'Globe',
    color: 'blue',
    feePercent: 1.8,
    minAmount: 50,
    requireApproval: false,
    isEnabled: true,
    sortOrder: 6,
  },
  {
    id: 'pay-voucher',
    name: 'บัตรกำนัล (Gift Voucher)',
    code: 'VOUCHER',
    type: 'voucher',
    iconName: 'Ticket',
    color: 'purple',
    feePercent: 0,
    minAmount: 0,
    requireApproval: true,
    isEnabled: true,
    sortOrder: 7,
  },
  {
    id: 'pay-credit',
    name: 'บัญชีวงเงินเชื่อ (Store Credit)',
    code: 'STORE_CREDIT',
    type: 'credit',
    iconName: 'Landmark',
    color: 'slate',
    feePercent: 0,
    minAmount: 0,
    requireApproval: true,
    isEnabled: true,
    sortOrder: 8,
  },
];

export const DEFAULT_DISCOUNT_PRESETS: DiscountPresetItem[] = [
  {
    id: 'disc-1',
    name: 'ส่วนลดสมาชิก VIP (VIP Member)',
    code: 'VIP_5',
    type: 'percentage',
    value: 5,
    minOrderAmount: 0,
    maxDiscountAmount: 500,
    requireManagerPin: false,
    isEnabled: true,
  },
  {
    id: 'disc-2',
    name: 'ส่วนลดพนักงาน (Staff Privilege)',
    code: 'STAFF_10',
    type: 'percentage',
    value: 10,
    minOrderAmount: 0,
    maxDiscountAmount: 1000,
    requireManagerPin: false,
    isEnabled: true,
  },
  {
    id: 'disc-3',
    name: 'ส่วนลดผู้จัดการพิเศษ (Manager Approval)',
    code: 'MGR_15',
    type: 'percentage',
    value: 15,
    minOrderAmount: 500,
    maxDiscountAmount: 3000,
    requireManagerPin: true,
    isEnabled: true,
  },
  {
    id: 'disc-4',
    name: 'ลดล้างสต็อก (Clearance)',
    code: 'CLR_20',
    type: 'percentage',
    value: 20,
    minOrderAmount: 0,
    maxDiscountAmount: 5000,
    requireManagerPin: true,
    isEnabled: true,
  },
  {
    id: 'disc-5',
    name: 'คูปองลด 50 บาท (Voucher 50 THB)',
    code: 'COUPON_50',
    type: 'fixed',
    value: 50,
    minOrderAmount: 300,
    maxDiscountAmount: 50,
    requireManagerPin: false,
    isEnabled: true,
  },
  {
    id: 'disc-6',
    name: 'ส่วนลดวันเกิด 100 บาท (Birthday Gift)',
    code: 'BDAY_100',
    type: 'fixed',
    value: 100,
    minOrderAmount: 500,
    maxDiscountAmount: 100,
    requireManagerPin: false,
    isEnabled: true,
  },
];

export const DEFAULT_TAX_BRACKETS: TaxBracketItem[] = [
  {
    id: 'tax-vat-7',
    name: 'ภาษีมูลค่าเพิ่ม 7% (VAT 7.00%)',
    rateBps: 700,
    isInclusive: true,
    isDefault: true,
    isEnabled: true,
    description: 'อัตราภาษีมูลค่าเพิ่มมาตรฐานแห่งประเทศไทย (รวมในราคาสินค้า)',
  },
  {
    id: 'tax-exempt-0',
    name: 'ยกเว้นภาษี 0% (Tax Exempt)',
    rateBps: 0,
    isInclusive: true,
    isDefault: false,
    isEnabled: true,
    description: 'สินค้าและบริการที่ได้รับยกเว้นภาษีมูลค่าเพิ่มตามประมวลรัษฎากร',
  },
  {
    id: 'tax-svc-10',
    name: 'ค่าบริการ 10% (Service Charge)',
    rateBps: 1000,
    isInclusive: false,
    isDefault: false,
    isEnabled: true,
    description: 'ค่าบริการสำหรับการรับประทานที่ร้าน (คิดเพิ่มนอกราคาสินค้า)',
  },
  {
    id: 'tax-tourism-3',
    name: 'ภาษีบำรุงท้องถิ่น/การท่องเที่ยว 3%',
    rateBps: 300,
    isInclusive: false,
    isDefault: false,
    isEnabled: false,
    description: 'ภาษีเทศบาลเฉพาะพื้นที่ท่องเที่ยวหรือโรงแรม',
  },
];

export const DEFAULT_LOYALTY_CONFIG: LoyaltyEngineConfig = {
  enabled: true,
  pointsEarnRate: 25, // 25 THB = 1 Point
  pointsRedeemRate: 10, // 10 Points = 1 THB discount
  pointsExpiryDays: 365,
  allowNegativePoints: false,
  tiers: [
    {
      id: 'tier-bronze',
      name: 'Bronze Member',
      minSpend: 0,
      pointMultiplier: 1.0,
      discountPercent: 0,
      color: 'slate',
      badge: 'BRONZE',
      perks: ['สะสมแต้มปกติ 25 บาท = 1 แต้ม', 'รับแต้มพิเศษในวันเกิด'],
    },
    {
      id: 'tier-silver',
      name: 'Silver VIP',
      minSpend: 5000,
      pointMultiplier: 1.2,
      discountPercent: 3,
      color: 'cyan',
      badge: 'SILVER',
      perks: ['แต้มสะสม x1.2 เท่า', 'ส่วนลดอัตโนมัติ 3% ทุกยอดบิล', 'คูปองวันเกิด 100 บาท'],
    },
    {
      id: 'tier-gold',
      name: 'Gold Elite',
      minSpend: 20000,
      pointMultiplier: 1.5,
      discountPercent: 5,
      color: 'amber',
      badge: 'GOLD',
      perks: ['แต้มสะสม x1.5 เท่า', 'ส่วนลดอัตโนมัติ 5% ทุกยอดบิล', 'บริการช่องทางด่วนพิเศษ'],
    },
    {
      id: 'tier-platinum',
      name: 'Platinum Black',
      minSpend: 50000,
      pointMultiplier: 2.0,
      discountPercent: 10,
      color: 'purple',
      badge: 'PLATINUM',
      perks: ['แต้มสะสม x2.0 เท่า', 'ส่วนลดอัตโนมัติ 10% ทุกยอดบิล', 'สิทธิ์จอดรถและบริการ VIP Lounge'],
    },
  ],
};

export const DEFAULT_RECEIPT_TEMPLATE: ReceiptTemplateConfig = {
  logoUrl: '',
  storeName: 'PRODX Enterprise POS',
  branchName: 'สาขาหลัก (Headquarters - Flagship)',
  address: '999/9 ถนนพระราม 1 แขวงปทุมวัน เขตปทุมวัน กรุงเทพฯ 10330',
  phone: '02-123-4567',
  taxId: '0105559012345',
  posId: 'REG-BKK-001',
  headerMessage: 'ยินดีต้อนรับสู่ PRODX Store ขอบคุณที่ไว้วางใจในบริการของเรา',
  footerMessage: 'สินค้าซื้อแล้วสามารถเปลี่ยนคืนได้ภายใน 7 วัน พร้อมใบเสร็จรับเงินฉบับนี้',
  showTaxBreakdown: true,
  showCashierName: true,
  showCustomerLoyalty: true,
  showBarcode: true,
  showQrPayment: true,
  showWifiInfo: true,
  wifiSsid: 'PRODX_Guest_WiFi_5G',
  wifiPassword: 'welcometoprodx',
  paperWidth: '80mm',
};
