import crypto from 'node:crypto';
import type { CheckoutRequest, CheckoutResponse } from '../../src/adapters/types';
import type { CartLineItem, TenderPayment } from '../../src/domain/order';
import type { Product } from '../../src/domain/catalog';
import type { SqlQueryExecutor, TransactionalSqlExecutor } from '../db/transaction';

export class CheckoutValidationError extends Error { readonly code = 'CHECKOUT_VALIDATION_FAILED'; }
export class CheckoutConflictError extends Error { readonly code = 'CHECKOUT_CONFLICT'; }

type ProductRow = { id:string; store_id:string; category_id:string; sku:string; barcode:string; name:string; description:string|null; price_amount:string; cost_price_amount:string; currency:string; tax_rate_bps:number; current_stock:number; reorder_point:number; unit_of_measure:string; active:boolean };
type OrderRow = { id:string; order_number:string; idempotency_key:string; store_id:string; register_id:string; cashier_id:string; status:'server_confirmed'|'voided'|'refunded'; gross_subtotal_amount:string; item_discounts_amount:string; order_discount_amount:string; net_subtotal_amount:string; total_tax_amount:string; grand_total_amount:string; currency:string; total_items_count:number; created_at:Date; server_committed_at:Date };
type ItemRow = { id:string; product_id:string; quantity:number; unit_price_amount:string; item_discount_bps:number; line_subtotal_amount:string; line_tax_amount:string; line_total_amount:string; currency:string; category_id:string; sku:string; barcode:string; name:string; description:string|null; cost_price_amount:string; tax_rate_bps:number; reorder_point:number; unit_of_measure:string; current_stock:number; active:boolean };
type PaymentRow = { id:string; method:TenderPayment['method']; amount:string; tendered_cash:string|null; change_given:string|null; auth_code:string|null; card_last_four:string|null; terminal_reference:string|null; currency:string; created_at:Date };

const centsFromNumeric = (value: unknown, field: string): bigint => {
  const text = String(value);
  const match = /^(\d+)(?:\.(\d{1,2}))?$/.exec(text);
  if (!match) throw new CheckoutValidationError(`${field} must be a non-negative amount with at most 2 decimals.`);
  return BigInt(match[1]) * 100n + BigInt((match[2] ?? '').padEnd(2, '0') || '0');
};
const numericFromCents = (cents: bigint): string => `${cents / 100n}.${(cents % 100n).toString().padStart(2,'0')}`;
const safeNumber = (v: bigint, field:string): number => { const n=Number(v); if(!Number.isSafeInteger(n)) throw new CheckoutValidationError(`${field} exceeds safe integer range.`); return n; };
const moneyCents = (value: unknown, field:string): bigint => { const raw=(value as {amountInCents?:unknown}|undefined)?.amountInCents; if(typeof raw==='number'&&!Number.isSafeInteger(raw)) throw new CheckoutValidationError(`${field} is not a safe integer.`); const n=typeof raw==='number'||typeof raw==='string'||typeof raw==='bigint'?BigInt(raw as never):null; if(n===null||n<0n) throw new CheckoutValidationError(`${field} must be a non-negative integer minor-unit amount.`); return n; };

const authoritativeProduct = (row: ProductRow): Product => ({
  id:row.id, storeId:row.store_id, sku:row.sku, barcode:row.barcode, name:row.name, description:row.description ?? undefined,
  categoryId:row.category_id, price:{amountInCents:safeNumber(centsFromNumeric(row.price_amount,'price'),'price'),currency:row.currency},
  costPrice:{amountInCents:safeNumber(centsFromNumeric(row.cost_price_amount,'cost price'),'cost price'),currency:row.currency},
  taxRateBps:row.tax_rate_bps, currentStock:row.current_stock, reorderPoint:row.reorder_point, unitOfMeasure:row.unit_of_measure, active:row.active,
});

const readOrder = async (db:SqlQueryExecutor, storeId:string, key:string):Promise<OrderRow|null> => {
  const r=await db.query<OrderRow>(`SELECT id,order_number,idempotency_key,store_id,register_id,cashier_id,status,gross_subtotal_amount::text,item_discounts_amount::text,order_discount_amount::text,net_subtotal_amount::text,total_tax_amount::text,grand_total_amount::text,currency,total_items_count,created_at,server_committed_at FROM prodx_orders WHERE store_id=$1 AND idempotency_key=$2 LIMIT 1`,[storeId,key]);
  return r.rows[0]??null;
};
const readItems = async (db:SqlQueryExecutor, orderId:string, storeId:string):Promise<ItemRow[]> => {
  const r=await db.query<ItemRow>(`SELECT oi.id,oi.product_id,oi.quantity,oi.unit_price_amount::text,oi.item_discount_bps,oi.line_subtotal_amount::text,oi.line_tax_amount::text,oi.line_total_amount::text,oi.currency,p.category_id,p.sku,p.barcode,p.name,p.description,p.cost_price_amount::text,p.tax_rate_bps,p.reorder_point,p.unit_of_measure,p.current_stock,p.active FROM prodx_order_items oi JOIN prodx_products p ON p.id=oi.product_id AND p.store_id=oi.store_id WHERE oi.order_id=$1 AND oi.store_id=$2 ORDER BY oi.id`,[orderId,storeId]);
  return r.rows;
};
const readPayments = async (db:SqlQueryExecutor, orderId:string, storeId:string):Promise<PaymentRow[]> => {
  const r=await db.query<PaymentRow>(`SELECT id,method,amount::text,tendered_cash::text,change_given::text,auth_code,card_last_four,terminal_reference,currency,created_at FROM prodx_payments WHERE order_id=$1 AND store_id=$2 ORDER BY created_at,id`,[orderId,storeId]); return r.rows;
};
const toResponse = async (db:SqlQueryExecutor,row:OrderRow,cached:boolean):Promise<CheckoutResponse> => {
  const [irs,prs]=await Promise.all([readItems(db,row.id,row.store_id),readPayments(db,row.id,row.store_id)]);
  const items:CartLineItem[]=irs.map(i=>({lineId:i.id,product:{id:i.product_id,storeId:row.store_id,sku:i.sku,barcode:i.barcode,name:i.name,description:i.description??undefined,categoryId:i.category_id,price:{amountInCents:safeNumber(centsFromNumeric(i.unit_price_amount,'unit price'),'unit price'),currency:i.currency},costPrice:{amountInCents:safeNumber(centsFromNumeric(i.cost_price_amount,'cost price'),'cost price'),currency:i.currency},taxRateBps:i.tax_rate_bps,currentStock:i.current_stock,reorderPoint:i.reorder_point,unitOfMeasure:i.unit_of_measure,active:i.active},quantity:i.quantity,unitPrice:{amountInCents:safeNumber(centsFromNumeric(i.unit_price_amount,'unit price'),'unit price'),currency:i.currency},discountBps:i.item_discount_bps,lineSubtotal:{amountInCents:safeNumber(centsFromNumeric(i.line_subtotal_amount,'line subtotal'),'line subtotal'),currency:i.currency},lineTax:{amountInCents:safeNumber(centsFromNumeric(i.line_tax_amount,'line tax'),'line tax'),currency:i.currency},lineTotal:{amountInCents:safeNumber(centsFromNumeric(i.line_total_amount,'line total'),'line total'),currency:i.currency}}));
  const payments:TenderPayment[]=prs.map(p=>({id:p.id,method:p.method,amount:{amountInCents:safeNumber(centsFromNumeric(p.amount,'payment'),'payment'),currency:p.currency},tenderedCash:p.tendered_cash===null?undefined:{amountInCents:safeNumber(centsFromNumeric(p.tendered_cash,'tendered cash'),'tendered cash'),currency:p.currency},changeGiven:p.change_given===null?undefined:{amountInCents:safeNumber(centsFromNumeric(p.change_given,'change'),'change'),currency:p.currency},authCode:p.auth_code??undefined,cardLastFour:p.card_last_four??undefined,terminalReference:p.terminal_reference??undefined,timestamp:p.created_at.toISOString()}));
  return {success:true,serverConfirmed:true,idempotencyCached:cached,message:cached?'Checkout already committed; returning the existing transaction.':'Checkout committed.',order:{id:row.id,orderNumber:row.order_number,idempotencyKey:row.idempotency_key,storeId:row.store_id,registerId:row.register_id,cashierId:row.cashier_id,cashierName:'',items,totals:{grossSubtotal:{amountInCents:safeNumber(centsFromNumeric(row.gross_subtotal_amount,'gross subtotal'),'gross subtotal'),currency:row.currency},itemDiscounts:{amountInCents:safeNumber(centsFromNumeric(row.item_discounts_amount,'item discounts'),'item discounts'),currency:row.currency},orderDiscount:{amountInCents:safeNumber(centsFromNumeric(row.order_discount_amount,'order discount'),'order discount'),currency:row.currency},netSubtotal:{amountInCents:safeNumber(centsFromNumeric(row.net_subtotal_amount,'net subtotal'),'net subtotal'),currency:row.currency},totalTax:{amountInCents:safeNumber(centsFromNumeric(row.total_tax_amount,'tax'),'tax'),currency:row.currency},grandTotal:{amountInCents:safeNumber(centsFromNumeric(row.grand_total_amount,'grand total'),'grand total'),currency:row.currency},totalItemsCount:row.total_items_count},payments,status:row.status,serverCommittedAt:row.server_committed_at.toISOString(),createdAt:row.created_at.toISOString()}};
};

export const createCheckoutService=(db:TransactionalSqlExecutor)=>({
  async checkout(request:CheckoutRequest):Promise<CheckoutResponse>{
    if(!request.idempotencyKey?.trim()) throw new CheckoutValidationError('Idempotency key is required.');
    if(!request.storeId||!request.registerId||!request.cashierId) throw new CheckoutValidationError('Store, register and cashier are required.');
    if(request.items.length===0) throw new CheckoutValidationError('At least one item is required.');
    return db.transaction(async tx=>{
      const existing=await readOrder(tx,request.storeId,request.idempotencyKey); if(existing) return toResponse(tx,existing,true);
      const shift=await tx.query<{id:string}>(`SELECT sh.id FROM prodx_shifts sh JOIN prodx_registers r ON r.id=sh.register_id AND r.store_id=sh.store_id WHERE sh.store_id=$1 AND sh.register_id=$2 AND sh.cashier_id=$3 AND sh.status='open' AND r.status='active' FOR UPDATE`,[request.storeId,request.registerId,request.cashierId]);
      if(shift.rows.length!==1) throw new CheckoutConflictError('An active shift for this register and cashier is required.');
      const productIds=request.items.map(i=>i.product.id); if(new Set(productIds).size!==productIds.length) throw new CheckoutValidationError('Duplicate product lines are not allowed.');
      const products=await tx.query<ProductRow>(`SELECT id,store_id,category_id,sku,barcode,name,description,price_amount::text,cost_price_amount::text,currency,tax_rate_bps,current_stock,reorder_point,unit_of_measure,active FROM prodx_products WHERE store_id=$1 AND active=true AND id=ANY($2::uuid[]) FOR UPDATE`,[request.storeId,productIds]);
      if(products.rows.length!==productIds.length) throw new CheckoutValidationError('One or more products are unavailable in this store.');
      const authoritative=products.rows.map(authoritativeProduct);
      const byId=new Map(authoritative.map(p=>[p.id,p]));
      let gross=0n,itemDiscounts=0n,net=0n,tax=0n,totalItems=0;
      for(const item of request.items){
        if(!Number.isInteger(item.quantity)||item.quantity<=0) throw new CheckoutValidationError('Quantity must be positive.');
        if(!Number.isInteger(item.discountBps)||item.discountBps<0||item.discountBps>10000) throw new CheckoutValidationError('Discount must be between 0 and 10000 bps.');
        const p=byId.get(item.product.id)!; const unit=BigInt(p.price.amountInCents); const raw=unit*BigInt(item.quantity); const disc=(raw*BigInt(item.discountBps)+5000n)/10000n; const discounted=raw-disc; const lineTax=p.taxRateBps>0?(discounted*BigInt(p.taxRateBps)+BigInt(10000+p.taxRateBps)/2n)/BigInt(10000+p.taxRateBps):0n; gross+=raw;itemDiscounts+=disc;net+=discounted-lineTax;tax+=lineTax;totalItems+=item.quantity;
      }
      const orderDiscountBps=request.orderDiscountBps??0; if(!Number.isInteger(orderDiscountBps)||orderDiscountBps<0||orderDiscountBps>10000) throw new CheckoutValidationError('Order discount must be between 0 and 10000 bps.');
      const pre=gross-itemDiscounts; const orderDiscount=(pre*BigInt(orderDiscountBps)+5000n)/10000n; const grand=pre-orderDiscount; const adjustedNet=pre===0n?0n:(net*grand+pre/2n)/pre; const adjustedTax=pre===0n?0n:(tax*grand+pre/2n)/pre;
      const clientGrand=moneyCents(request.totals.grandTotal,'client grand total'); if(clientGrand!==grand) throw new CheckoutConflictError('Client total does not match server-authoritative total.');
      let paymentTotal=0n; for(const p of request.payments){ const a=moneyCents(p.amount,`payment ${p.id}`); if(a<=0n) throw new CheckoutValidationError('Payment amount must be positive.'); paymentTotal+=a; if(p.method==='cash'){const tendered=p.tenderedCash?moneyCents(p.tenderedCash,'tendered cash'):a;const change=p.changeGiven?moneyCents(p.changeGiven,'change given'):0n;if(tendered<a||change!==tendered-a)throw new CheckoutValidationError('Cash tender and change do not match payment amount.');} }
      if(paymentTotal!==grand) throw new CheckoutConflictError('Payment total does not match server-authoritative total.');
      const orderId=crypto.randomUUID(),orderNumber=`ORD-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${crypto.randomInt(100000,999999)}`;
      const ins=await tx.query<OrderRow>(`INSERT INTO prodx_orders(id,organization_id,store_id,register_id,cashier_id,shift_id,order_number,idempotency_key,gross_subtotal_amount,item_discounts_amount,order_discount_amount,net_subtotal_amount,total_tax_amount,grand_total_amount,currency,total_items_count,notes) SELECT $1,organization_id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16 FROM prodx_stores WHERE id=$2 ON CONFLICT(store_id,idempotency_key) DO NOTHING RETURNING id,order_number,idempotency_key,store_id,register_id,cashier_id,status,gross_subtotal_amount::text,item_discounts_amount::text,order_discount_amount::text,net_subtotal_amount::text,total_tax_amount::text,grand_total_amount::text,currency,total_items_count,created_at,server_committed_at`,[orderId,request.storeId,request.registerId,request.cashierId,shift.rows[0].id,orderNumber,request.idempotencyKey,numericFromCents(gross),numericFromCents(itemDiscounts),numericFromCents(orderDiscount),numericFromCents(adjustedNet),numericFromCents(adjustedTax),numericFromCents(grand),products.rows[0].currency,totalItems,request.notes??null]);
      if(ins.rows.length===0){const concurrent=await readOrder(tx,request.storeId,request.idempotencyKey);if(!concurrent)throw new CheckoutConflictError('Idempotency conflict could not be resolved.');return toResponse(tx,concurrent,true);} const order=ins.rows[0];
      for(const item of request.items){ const p=byId.get(item.product.id)!; const unit=BigInt(p.price.amountInCents),raw=unit*BigInt(item.quantity),disc=(raw*BigInt(item.discountBps)+5000n)/10000n,discounted=raw-disc,lineTax=p.taxRateBps>0?(discounted*BigInt(p.taxRateBps)+BigInt(10000+p.taxRateBps)/2n)/BigInt(10000+p.taxRateBps):0n,lineNet=discounted-lineTax; const stock=await tx.query<{current_stock:number}>(`UPDATE prodx_products SET current_stock=current_stock-$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND store_id=$3 AND current_stock>=$1 RETURNING current_stock`,[item.quantity,item.product.id,request.storeId]); if(stock.rows.length!==1) throw new CheckoutConflictError(`Insufficient stock for product ${item.product.id}.`); await tx.query(`INSERT INTO prodx_order_items(id,organization_id,store_id,order_id,product_id,quantity,unit_price_amount,item_discount_bps,line_subtotal_amount,line_tax_amount,line_total_amount,currency) SELECT $1,organization_id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 FROM prodx_products WHERE id=$4 AND store_id=$2`,[crypto.randomUUID(),request.storeId,order.id,item.product.id,item.quantity,numericFromCents(unit),item.discountBps,numericFromCents(lineNet),numericFromCents(lineTax),numericFromCents(discounted),p.price.currency]); await tx.query(`INSERT INTO prodx_inventory_ledger(id,organization_id,store_id,product_id,quantity_delta,resulting_stock,reason,reference_id,performed_by_user_id) SELECT $1,organization_id,store_id,product_id,$2,$3,'sale_deduction',$4,$5 FROM prodx_products WHERE id=$6 AND store_id=$7`,[crypto.randomUUID(),-item.quantity,stock.rows[0].current_stock,order.id,request.cashierId,item.product.id,request.storeId]); }
      for(const p of request.payments){const amount=moneyCents(p.amount,`payment ${p.id}`);await tx.query(`INSERT INTO prodx_payments(id,organization_id,store_id,order_id,method,amount,tendered_cash,change_given,auth_code,card_last_four,terminal_reference,currency) SELECT $1,organization_id,store_id,$2,$3,$4,$5,$6,$7,$8,$9,$10 FROM prodx_orders WHERE id=$2 AND store_id=$11`,[p.id,order.id,p.method,numericFromCents(amount),p.tenderedCash?numericFromCents(moneyCents(p.tenderedCash,'tendered cash')):null,p.changeGiven?numericFromCents(moneyCents(p.changeGiven,'change given')):null,p.authCode??null,p.cardLastFour??null,p.terminalReference??null,p.amount.currency,request.storeId]);if(p.method==='cash'){const tendered=p.tenderedCash?moneyCents(p.tenderedCash,'tendered cash'):amount,change=p.changeGiven?moneyCents(p.changeGiven,'change given'):0n;const cashIn=tendered-change;await tx.query(`INSERT INTO prodx_cash_movements(id,organization_id,store_id,shift_id,type,amount,reason,performed_by_user_id,currency) SELECT $1,organization_id,store_id,shift_id,'cash_sale',$2,'POS sale',$3,$4 FROM prodx_orders WHERE id=$5 AND store_id=$6`,[crypto.randomUUID(),numericFromCents(cashIn),request.cashierId,p.amount.currency,order.id,request.storeId]);}}
      await tx.query(`INSERT INTO prodx_audit_log(id,organization_id,store_id,register_id,user_id,action,severity,details) SELECT $1,organization_id,store_id,register_id,cashier_id,'order_checkout_committed','info',$2::jsonb FROM prodx_orders WHERE id=$3 AND store_id=$4`,[crypto.randomUUID(),JSON.stringify({orderId:order.id,idempotencyKey:request.idempotencyKey,grandTotal:numericFromCents(grand)}),order.id,request.storeId]);
      return toResponse(tx,order,false);
    });
  }
});
