import crypto from 'node:crypto';
import express, { type NextFunction, type Request, type Response } from 'express';
import type { ApiErrorBody, AuthenticateRequest, AuthorizeRequest, RequestContext, RequestPrincipal } from './types';

declare global { namespace Express { interface Request { id: string; prodxContext?: RequestContext; } } }

export type BackendBoundaryOptions = { authenticateRequest: AuthenticateRequest; authorizeRequest?: AuthorizeRequest; configureRoutes?: (app: express.Express) => void; publicPaths?: readonly string[]; };
const sendError=(response:Response,status:number,code:string,message:string,requestId:string,details?:unknown):void=>{const body:ApiErrorBody={error:{code,message,requestId,...(details===undefined?{}:{details})}};response.status(status).json(body);};
const requestId=(request:Request):string=>{const supplied=request.header('x-request-id');return supplied&&supplied.length<=128?supplied:crypto.randomUUID();};
export const requirePermission=(permission:string)=>async(request:Request,response:Response,next:NextFunction):Promise<void>=>{const context=request.prodxContext;if(!context){sendError(response,500,'REQUEST_CONTEXT_MISSING','Request context is required.',request.id);return;}const authorizer=request.app.locals.prodxAuthorize as AuthorizeRequest|undefined;if(!authorizer){sendError(response,500,'AUTHORIZATION_NOT_CONFIGURED','Authorization is not configured.',context.requestId);return;}if(!(await authorizer(context,permission))){sendError(response,403,'FORBIDDEN','The requested capability is not authorized.',context.requestId);return;}next();};
const attachRequestId=(request:Request,response:Response,next:NextFunction):void=>{const id=requestId(request);request.id=id;response.setHeader('x-request-id',id);next();};
const observeRequest=(request:Request,response:Response,next:NextFunction):void=>{const started=process.hrtime.bigint();response.once('finish',()=>{const durationMs=Number(process.hrtime.bigint()-started)/1_000_000;console.info(JSON.stringify({event:'http_request',requestId:request.id,method:request.method,path:request.path,status:response.statusCode,durationMs:Math.round(durationMs*100)/100}));});next();};
const authenticate=(authenticator:AuthenticateRequest,publicPaths:ReadonlySet<string>)=>async(request:Request,response:Response,next:NextFunction):Promise<void>=>{if(publicPaths.has(request.path)){next();return;}try{const principal:RequestPrincipal|null=await authenticator(request);if(!principal){sendError(response,401,'UNAUTHENTICATED','Authentication is required.',request.id);return;}request.prodxContext={requestId:request.id,principal};next();}catch{sendError(response,401,'UNAUTHENTICATED','Authentication could not be verified.',request.id);}};
export const createApp=(options:BackendBoundaryOptions)=>{const app=express();app.disable('x-powered-by');app.use(express.json({limit:'1mb'}));app.use(attachRequestId);app.use(observeRequest);app.locals.prodxAuthorize=options.authorizeRequest;app.use(authenticate(options.authenticateRequest,new Set(options.publicPaths??[])));app.get('/api/v1/health',(_request,response)=>{response.json({status:'ok'});});options.configureRoutes?.(app);app.use((_request,response)=>{sendError(response,404,'NOT_FOUND','Route not found.',response.getHeader('x-request-id')?.toString()??'unknown');});app.use((error:unknown,request:Request,response:Response,_next:NextFunction)=>{const details=process.env.NODE_ENV==='production'?undefined:error instanceof Error?error.message:error;sendError(response,500,'INTERNAL_ERROR','An unexpected server error occurred.',request.id,details);});return app;};
